# Fetches the full IEEE MAC-vendor (OUI) registry and writes it as a vendored JS asset
# for Network_Visualizer to look up client vendors from. Deliberately a separate script
# from the crawler: this is the only piece of PS_NetworkMapper that needs internet
# egress (to IEEE), which the switch-crawling scripts never do and shouldn't need to -
# a real network-boundary reason to keep it isolated, not just tidiness. Re-run this
# occasionally to pick up newly-registered vendors; nothing else in the repo depends on
# it running automatically.
#
# Modeled on the sibling PS_IPv4Scanner/getOUI.ps1, which already does this exact
# IEEE-fetch-and-parse job for a different tool in this repo - same source, same TLS/
# User-Agent handling, same "base 16" line format - just written out as a JS asset
# instead of a pipe-delimited text file, since the consumer here is a browser, not
# another PowerShell script.
[CmdletBinding()]
param(
    # $PSScriptRoot is Network_Mapper/lib/ - the target is the sibling top-level
    # Network_Visualizer/ folder's src/vendor/, two levels up and back down.
    [string]$OutputPath = (Join-Path $PSScriptRoot "..\..\Network_Visualizer\src\vendor\oui-data.js")
)

[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12

$Session = New-Object Microsoft.PowerShell.Commands.WebRequestSession
$Headers = @{ "User-Agent" = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0 Safari/537.36" }

Write-Host "Fetching IEEE OUI registry (standards-oui.ieee.org/oui/oui.txt)..." -ForegroundColor Cyan
$RawText = (Invoke-WebRequest -Uri "https://standards-oui.ieee.org/oui/oui.txt" -WebSession $Session -Headers $Headers).Content

# Real line format (confirmed against the live endpoint):
#   286FB9     (base 16)\t\tNokia Shanghai Bell Co., Ltd.
# Address lines that follow each entry don't match this pattern and are skipped for free.
$Entries = [ordered]@{}
foreach ($Line in ($RawText -split "[\r\n]")) {
    if ($Line -match "^(?<prefix>[A-Fa-f0-9]{6})\s*\(base 16\)\s*(?<vendor>.+)$") {
        $Prefix = $Matches.prefix.ToUpper()
        $Vendor = $Matches.vendor.Trim()
        if (-not $Entries.Contains($Prefix)) { $Entries[$Prefix] = $Vendor }
    }
}

if ($Entries.Count -eq 0) { throw "Parsed zero OUI entries - IEEE's response format may have changed. Inspect the raw response before assuming the fetch itself failed." }

# JSON is a strict subset of JS object-literal syntax, so ConvertTo-Json's output can be
# assigned directly to window.OUI_DATABASE without any hand-escaping of vendor names that
# contain quotes/backslashes/etc.
$JsonBody = $Entries | ConvertTo-Json -Depth 2 -Compress

$OutputDir = Split-Path $OutputPath -Parent
if (-not (Test-Path $OutputDir)) { New-Item -ItemType Directory -Path $OutputDir -Force | Out-Null }

$Header = "// Auto-generated by Update-OuiDatabase.ps1 from https://standards-oui.ieee.org/oui/oui.txt`n// Generated: $(Get-Date -Format 'o') - $($Entries.Count) entries.`n// Loaded as a classic <script> tag (not fetched) so it works under file:// with no`n// local web server - see graph-layout.js's footer comment for why that constraint exists.`n"
$JsBody = "window.OUI_DATABASE = $JsonBody;`n"
Set-Content -Path $OutputPath -Value ($Header + $JsBody) -Encoding utf8 -NoNewline

Write-Host "Wrote $($Entries.Count) OUI entries to $OutputPath ($([math]::Round((Get-Item $OutputPath).Length / 1MB, 2)) MB)" -ForegroundColor Green
