# Fetches the full IEEE MAC-vendor (OUI) registry and writes it as a vendored JS asset for
# web-src to look up client vendors from. Kept separate from the crawler since it's the only
# part of PS_NetworkMapper that needs internet egress. Re-run occasionally to pick up newly
# registered vendors; nothing else depends on it running automatically.
[CmdletBinding()]
param(
    # $PSScriptRoot is PS_NetworkMapper/lib/; target is the sibling web-src/vendor/.
    [string]$OutputPath = (Join-Path $PSScriptRoot "..\web-src\vendor\oui-data.js")
)

[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12

$Session = New-Object Microsoft.PowerShell.Commands.WebRequestSession
$Headers = @{ "User-Agent" = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0 Safari/537.36" }

Write-Host "Fetching IEEE OUI registry (standards-oui.ieee.org/oui/oui.txt)..." -ForegroundColor Cyan
try {
    $RawText = (Invoke-WebRequest -Uri "https://standards-oui.ieee.org/oui/oui.txt" -WebSession $Session -Headers $Headers).Content
} catch {
    throw "Failed to fetch the IEEE OUI registry: $_"
}

# Real line format: "286FB9     (base 16)\t\tNokia Shanghai Bell Co., Ltd." - address
# lines that follow each entry don't match this pattern and are skipped for free.
$Entries = [ordered]@{}
foreach ($Line in ($RawText -split "[\r\n]")) {
    if ($Line -match "^(?<prefix>[A-Fa-f0-9]{6})\s*\(base 16\)\s*(?<vendor>.+)$") {
        $Prefix = $Matches.prefix.ToUpper()
        $Vendor = $Matches.vendor.Trim()
        if (-not $Entries.Contains($Prefix)) { $Entries[$Prefix] = $Vendor }
    }
}

if ($Entries.Count -eq 0) { throw "Parsed zero OUI entries - IEEE's response format may have changed. Inspect the raw response before assuming the fetch itself failed." }

# The real registry has 30k+ entries; a dropped connection mid-download still yields a
# well-formed prefix of it, which would silently pass the zero-count check above and
# overwrite a good database with an incomplete one. Below this threshold, treat it as a
# failed/partial fetch rather than a legitimately shrunk registry.
if ($Entries.Count -lt 10000) { throw "Only parsed $($Entries.Count) OUI entries (expected 30,000+) - the download likely failed partway through. Not overwriting $OutputPath." }

# JSON is a strict subset of JS object-literal syntax, so this can be assigned directly to
# window.OUI_DATABASE with no hand-escaping needed.
$JsonBody = $Entries | ConvertTo-Json -Depth 2 -Compress

$OutputDir = Split-Path $OutputPath -Parent
if (-not (Test-Path $OutputDir)) { New-Item -ItemType Directory -Path $OutputDir -Force | Out-Null }

$Header = "// Auto-generated by Update-OuiDatabase.ps1 from https://standards-oui.ieee.org/oui/oui.txt`n// Generated: $(Get-Date -Format 'o') - $($Entries.Count) entries.`n// Loaded as a classic <script> tag (not fetched) so it works under file:// with no`n// local web server - see graph-layout.js's footer comment for why that constraint exists.`n"
$JsBody = "window.OUI_DATABASE = $JsonBody;`n"
Set-Content -Path $OutputPath -Value ($Header + $JsBody) -Encoding utf8 -NoNewline

Write-Host "Wrote $($Entries.Count) OUI entries to $OutputPath ($([math]::Round((Get-Item $OutputPath).Length / 1MB, 2)) MB)" -ForegroundColor Green
