# Fetches the IEEE MAC-vendor (OUI) registry and writes it as a vendored JS asset for web-src. The
# only part of PS_NetworkMapper needing internet egress; nothing runs it automatically.
[CmdletBinding()]
param(
    # $PSScriptRoot is PS_NetworkMapper/lib/; target is the sibling web-src/vendor/.
    [string]$OutputPath = (Join-Path $PSScriptRoot "..\web-src\vendor\oui-data.js")
)

. (Join-Path $PSScriptRoot "FileHelpers.ps1")

[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12

$Session = New-Object Microsoft.PowerShell.Commands.WebRequestSession
$Headers = @{ "User-Agent" = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0 Safari/537.36" }

Write-Host "Fetching IEEE OUI registry (standards-oui.ieee.org/oui/oui.txt)..." -ForegroundColor Cyan
# Re-read as explicit UTF-8 rather than trusting Invoke-WebRequest's .Content decode, which follows
# the runtime default and mojibakes IEEE's non-ASCII vendor names.
$TempFile = New-TemporaryFile
try {
    try {
        Invoke-WebRequest -Uri "https://standards-oui.ieee.org/oui/oui.txt" -WebSession $Session -Headers $Headers -OutFile $TempFile.FullName
    } catch {
        throw "Failed to fetch the IEEE OUI registry: $_"
    }
    $RawText = Get-Content $TempFile.FullName -Raw -Encoding UTF8
} finally {
    Remove-Item $TempFile.FullName -Force -ErrorAction SilentlyContinue
}

# Address lines following each entry don't match this pattern and are skipped for free.
$Entries = [ordered]@{}
foreach ($Line in ($RawText -split "[\r\n]")) {
    if ($Line -match "^(?<prefix>[A-Fa-f0-9]{6})\s*\(base 16\)\s*(?<vendor>.+)$") {
        $Prefix = $Matches.prefix.ToUpper()
        $Vendor = $Matches.vendor.Trim()
        if (-not $Entries.Contains($Prefix)) { $Entries[$Prefix] = $Vendor }
    }
}

if ($Entries.Count -eq 0) { throw "Parsed zero OUI entries - IEEE's response format may have changed. Inspect the raw response before assuming the fetch itself failed." }

# A connection dropped mid-download still yields a well-formed prefix, which would pass the
# zero-count check above and overwrite a good database with an incomplete one.
if ($Entries.Count -lt 10000) { throw "Only parsed $($Entries.Count) OUI entries (expected 30,000+) - the download likely failed partway through. Not overwriting $OutputPath." }

# JSON is a strict subset of JS object-literal syntax, so it can be assigned directly.
$JsonBody = $Entries | ConvertTo-Json -Depth 2 -Compress

$OutputDir = Split-Path $OutputPath -Parent
if (-not (Test-Path $OutputDir)) { New-Item -ItemType Directory -Path $OutputDir -Force | Out-Null }

$Header = "// Auto-generated by Update-OuiDatabase.ps1 from https://standards-oui.ieee.org/oui/oui.txt`n// Generated: $(Get-Date -Format 'o') - $($Entries.Count) entries.`n// Loaded as a classic <script> tag (not fetched) so it works under file:// with no`n// local web server - see graph-layout.js's footer comment for why that constraint exists.`n"
$JsBody = "window.OUI_DATABASE = $JsonBody;`n"

# Atomic so a crash/disk-full mid-write can't truncate the checked-into-git vendored asset.
Set-FileContentAtomic -DestinationPath $OutputPath -Content ($Header + $JsBody) -Encoding utf8 -NoNewline

Write-Host "Wrote $($Entries.Count) OUI entries to $OutputPath ($([math]::Round((Get-Item $OutputPath).Length / 1MB, 2)) MB)" -ForegroundColor Green
